"""IO point mappings and VFD configurations"""

# All IO points
IO_POINTS = {
    "LPumpPhaseA": {"type": "AI", "readable_name": "LH Pump Current (A)"},
    "LPumpPhaseB": {"type": "AI", "readable_name": "LH Pump Current (B)"},
    "LPumpPhaseC": {"type": "AI", "readable_name": "LH Pump Current (C)"},
    "RPumpPhaseA": {"type": "AI", "readable_name": "RH Pump Current (A)"},
    "RPumpPhaseB": {"type": "AI", "readable_name": "RH Pump Current (B)"},
    "RPumpPhaseC": {"type": "AI", "readable_name": "RH Pump Current (C)"},
    "LCutterPhaseA": {"type": "AI", "readable_name": "LH Cutter Current (A)"},
    "LCutterPhaseB": {"type": "AI", "readable_name": "LH Cutter Current (B)"},
    "LCutterPhaseC": {"type": "AI", "readable_name": "LH Cutter Current (C)"},
    "RCutterPhaseA": {"type": "AI", "readable_name": "RH Cutter Current (A)"},
    "RCutterPhaseB": {"type": "AI", "readable_name": "RH Cutter Current (B)"},
    "RCutterPhaseC": {"type": "AI", "readable_name": "RH Cutter Current (C)"},
    "LTramPhaseA": {"type": "AI", "readable_name": "LH Haulage Current (A)"},
    "LTramPhaseB": {"type": "AI", "readable_name": "LH Haulage Current (B)"},
    "LTramPhaseC": {"type": "AI", "readable_name": "LH Haulage Current (C)"},
    "RTramPhaseA": {"type": "AI", "readable_name": "RH Haulage Current (A)"},
    "RTramPhaseB": {"type": "AI", "readable_name": "RH Haulage Current (B)"},
    "RTramPhaseC": {"type": "AI", "readable_name": "RH Haulage Current (C)"},
    "LumpBkrPhaseA": {"type": "AI", "readable_name": "Lumpbreaker Current (A)"},
    "LumpBkrPhaseB": {"type": "AI", "readable_name": "Lumpbreaker Current (B)"},
    "LumpBkrPhaseC": {"type": "AI", "readable_name": "Lumpbreaker Current (C)"},
    "LPumpRTD": {"type": "AI", "readable_name": "LH Pump Temp"},
    "RPumpRTD": {"type": "AI", "readable_name": "RH Pump Temp"},
    "LCutterRTD": {"type": "AI", "readable_name": "LH Cutter Temp"},
    "RCutterRTD": {"type": "AI", "readable_name": "RH Cutter Temp"},
    "LTramRTD": {"type": "AI", "readable_name": "LH Haulage Temp"},
    "RTramRTD": {"type": "AI", "readable_name": "RH Haulage Temp"},
    "LumpBkrRTD": {"type": "AI", "readable_name": "Lumpbreaker Temp"},
    "ControllerRTD": {"type": "AI", "readable_name": "Controller Temp"},
    "LineVoltageA": {"type": "AI", "readable_name": "Line Voltage (A)"},
    "LineVoltageB": {"type": "AI", "readable_name": "Line Voltage (B)"},
    "LineVoltageC": {"type": "AI", "readable_name": "Line Voltage (C)"},
    "LineCurrentA": {"type": "AI", "readable_name": "Line Current (A)"},
    "LineCurrentB": {"type": "AI", "readable_name": "Line Current (B)"},
    "LineCurrentC": {"type": "AI", "readable_name": "Line Current (C)"},
    "ControlVoltage": {"type": "AI", "readable_name": "Control Voltage"},
    "VFDActSpeed": {"type": "AI", "readable_name": "Actual Speed"},
    "VFDDesSpeed": {"type": "AI", "readable_name": "Desired Speed"},
    "lHydraulicPress": {"type": "AI", "readable_name": "LH Hydraulic Pressure"},
    "rHydraulicPress": {"type": "AI", "readable_name": "RH Hydraulic Pressure"},
    "lDrumH2OFlow": {"type": "AI", "readable_name": "LH Drum H2O Flow"},
    "rDrumH2OFlow": {"type": "AI", "readable_name": "RH Drum H2O Flow"},
    "lCutterH2OFlow": {"type": "AI", "readable_name": "LH Cutter H2O Flow"},
    "rCutterH2OFlow": {"type": "AI", "readable_name": "RH Cutter H2O Flow"},
    "lDrumH2OPress": {"type": "AI", "readable_name": "LH Drum H2O Pressure"},
    "rDrumH2OPress": {"type": "AI", "readable_name": "RH Drum H2O Pressure"},
    "lCutterH2OPress": {"type": "AI", "readable_name": "LH Cutter H2O Pressure"},
    "rCutterH2OPress": {"type": "AI", "readable_name": "RH Cutter H2O Pressure"},
    "LeftVFDTemp": {"type": "AI", "readable_name": "LH VFD Temp"},
    "RightVFDTemp": {"type": "AI", "readable_name": "RH VFD Temp"},
    "BussSupplyTemp": {"type": "AI", "readable_name": "Bus Supply Temp"},
    "LeftBusVoltage": {"type": "AI", "readable_name": "LH Bus Volts"},
    "RightBusVoltage": {"type": "AI", "readable_name": "RH Bus Volts"},
    "rRangingarmTemp": {"type": "AI", "readable_name": "RH Arm Temp"},
    "lRangingarmTemp": {"type": "AI", "readable_name": "LH Arm Temp"},
    "lTramOilTemp": {"type": "AI", "readable_name": "LH Tram Oil Temp"},
    "rTramOilTemp": {"type": "AI", "readable_name": "RH Tram Oil Temp"},
    "lHaulBearingRTD": {"type": "AI", "readable_name": "LH  Bearing Temp"},
    "rHaulBearingRTD": {"type": "AI", "readable_name": "RH  Bearing Temp"},
    "HaulDir": {"type": "SI", "readable_name": "Haulage Direction"},
    "SupportNo": {"type": "AI", "readable_name": "Support Number"},
    "MetersToHeadSIRSA": {"type": "AI", "readable_name": "Meters to MG"},
    "HaulageWtrFlw1": {"type": "AI", "readable_name": "Haulage H2O Flow 1"},
    "HaulageWtrFlw2": {"type": "AI", "readable_name": "Haulage H2O Flow 2"},
    "HaulageWtrPres1": {"type": "AI", "readable_name": "Haulage H2O Pressure 1"},
    "HaulageWtrPres2": {"type": "AI", "readable_name": "Haulage H2O Pressure 2"},
    "MMX01": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "MMX Comms "},
    "LPUMPMCT": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "LH Pump MCT Comms"},
    "RPUMPMCT": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "RH Pump MCT Comms"},
    "LCUTMCT": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "LH Cutter MCT Comms"},
    "RCUTMCT": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "RH Cutter MCT Comms"},
    "LBKRMCT": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "Lump MCT Comms"},
    "XFMRMCT": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "Xfmr MCT Comms"},
    "ESX3XM01": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "3XM1 Comms"},
    "ESX3XM02": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "3XM2 Comms"},
    "ESX3XM03": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "ESX3XM03"},
    "ESX3XM04": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "ESX3XM04"},
    "LBOOMINC": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "LH Incimometer Comms"},
    "RBOOMINC": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "RH Incimometer Comms"},
    "LUMPINC": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "Lump Inclinometer Comms"},
    "PITCHROLLINC": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "Pitch and Roll Comms"},
    "lHaulAbsEnc": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "LH Haul Encoder Comms"},
    "rHaulAbsEnc": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "RH Haul Encoder Comms"},
    "lRaAbsEnc": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "LH Arm Encoder Comms"},
    "rRaAbsEnc": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "RH Arm Encoder Comms"},
    "lCowlAbsEnc": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "LH Cowl Encoder Comms"},
    "rCowlAbsEnc": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "RH Cowl Encoder Comms"},
    "RH_GIO_1": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "RH GIO 1 Comms"},
    "RH_GIO_2": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "RH GIO 2 Comms"},
    "LH_GIO_1": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "LH GIO 1 Comms"},
    "LH_GIO_2": {"type": "NDSTAT", "valueType": "devOk", "readable_name": "LH GIO 2 Comms"},
    "Mcut_LShoeHt": {"type": "SI", "readable_name": "Mcut_LShoeHt"},
    "Mcut_RShoeHt": {"type": "SI", "readable_name": "Mcut_RShoeHt"},
    "ShrStepNo": {"type": "SI", "readable_name": "ASA Step Number"},
    "ASA_BmMethAndMode_L": {"type": "SI", "readable_name": "LH Boom Mode"},
    "ASA_BmMethAndMode_R": {"type": "SI", "readable_name": "RH Boom Mode"},
    "Mcut_RollAngle": {"type": "AI", "readable_name": "Roll Angle"},
    "Mcut_PitchAngle": {"type": "AI", "readable_name": "Pitch Angle"},
    "Mcut_PrevPitch": {"type": "AI", "readable_name": "Previous Pitch Angle"},
    "Mcut_LBoomAng": {"type": "AI", "readable_name": "LH Boom Angle"},
    "Mcut_RBoomAng": {"type": "AI", "readable_name": "RH Boom Angle"},
    "Mcut_LRelBmHt": {"type": "SI", "readable_name": "LH Actual  Height"},
    "Mcut_RRelBmHt": {"type": "SI", "readable_name": "RH Actual  Height"},
    "Mcut_LRefBmHt": {"type": "SI", "readable_name": "LH Desired Height"},
    "Mcut_RRefBmHt": {"type": "SI", "readable_name": "RH Desired Height"},
    "TopPickHt_L": {"type": "SI", "readable_name": "LH Top Pick Height"},
    "TopPickHt_R": {"type": "SI", "readable_name": "RH Top Pick Height"},
    "BottomPickHt_L": {"type": "SI", "readable_name": "LH Bottom Pick Height"},
    "BottomPickHt_R": {"type": "SI", "readable_name": "RH Bottom Pick Height"},
    "Mcut_DesExt": {"type": "SI", "readable_name": "Desired Extraction"},
    "Mcut_ActExt": {"type": "SI", "readable_name": "Actual Extraction"},
    "asaMode": {"type": "LI", "readable_name": "ASA Mode"},
    "Mcut_PitchHt_L": {"type": "SI", "readable_name": "LH Pitch Comp"},
    "Mcut_PitchHt_R": {"type": "SI", "readable_name": "RH Pitch Comp"},
    "ActualCutPitchCorr": {"type": "SI", "readable_name": "Actual Cut PIT Correction"},
    "CalculatedPitchCorr": {"type": "SI", "readable_name": "Calculated PIT Correction"},
    "RoofCutPIT": {"type": "SI", "readable_name": "RRF PIT Roof Drum Status "},
    "SupportNo_LH": {"type": "AI", "readable_name": "LH Support Number"},
    "SupportNo_RH": {"type": "AI", "readable_name": "RH Support Number"},
    "lOilTemp": {"type": "AI", "readable_name": "LH Oil Temp"},
    "rOilTemp": {"type": "AI", "readable_name": "RH Oil Temp"},
    "lAux1Temp": {"type": "AI", "readable_name": "LH Aux 1 Temp"},
    "lAux2Temp": {"type": "AI", "readable_name": "LH Aux 2 Temp"},
    "rAux1Temp": {"type": "AI", "readable_name": "RH Aux 1 Temp"},
    "rAux2Temp": {"type": "AI", "readable_name": "RH Aux 2 Temp"},
    "TrlCblStrnGauge": {"type": "AI", "readable_name": "Strain Gauge"},
    "lHydraulicFlow": {"type": "AI", "readable_name": "LH Hydraulic Flow"},
    "rHydraulicFlow": {"type": "AI", "readable_name": "RH Hydraulic Flow"},
    "HaulageXfmrRTD": {"type": "AI", "readable_name": "Haulage Transformer Temp"},
    "lCoolingWtrTemp": {"type": "AI", "readable_name": "LH Cooling Water Temp"},
    "rCoolingWtrTemp": {"type": "AI", "readable_name": "RH Cooling Water Temp"},
    "waterPress1": {"type": "AI", "readable_name": "Water Pressure 1"},
    "waterPress2": {"type": "AI", "readable_name": "Water Pressure 2"},
    "waterFlow1": {"type": "AI", "readable_name": "Water Flow 1"},
    "waterFlow2": {"type": "AI", "readable_name": "Water Flow 2"},
    "lHydraulicPressDiff": {"type": "AI", "readable_name": "LH Hyd Press Differential"},
    "rHydraulicPressDiff": {"type": "AI", "readable_name": "RH Hyd Press Differential"},
}

# Vfd points (reversed mapping because of duplicate key)
VFD_POINTS = {
    "LH VFD Link Volts": {"type": "link_volts", "name": "LEFT_VFD"},
    "RH VFD Link Volts": {"type": "link_volts", "name": "RIGHT_VFD"},

    "LH VFD Motor Volts": {"type": "motor_volt", "name": "LEFT_VFD"},
    "RH VFD Motor Volts": {"type": "motor_volt", "name": "RIGHT_VFD"},

    "LH VFD Ref Freq": {"type": "frequency_ref", "name": "LEFT_VFD"},
    "RH VFD Ref Freq": {"type": "frequency_ref", "name": "RIGHT_VFD"},

    "LH VFD Actual Freq": {"type": "frequency_actual", "name": "LEFT_VFD"},
    "RH VFD Actual Freq": {"type": "frequency_actual", "name": "RIGHT_VFD"},

    # These Comms are type comms_wd_trip which is equivalent to devOk in the Node Status Table 
    # But is a 1 if there is no comms instead of a 0
    "LH VFD Comms": {"type": "comms_wd_trip", "name": "LEFT_VFD"},
    "RH VFD Comms": {"type": "comms_wd_trip", "name": "RIGHT_VFD"},
    "Regen Comms": {"type": "comms_wd_trip", "name": "REGEN_VFD"},
}

# IO types
IO_TYPES = {
    "J_DI_TYPE": "DigitalInput@0",
    "0": "DigitalInput",
    "J_DO_TYPE": "DigitalOutput@0",
    "1": "DigitalOutput",
    "J_AI_TYPE": "AnalogInput@0",
    "2": "AnalogInput",
    "J_LI_TYPE": "LongInput@0",
    "9": "LongInput",
    "J_LO_TYPE": "LongOutput@0",
    "10": "LongOutput",
    "J_SI_TYPE": "ShortInput@0",
    "7": "ShortInput",
    "J_SO_TYPE": "ShortOutput@0",
    "8": "ShortOutput",
    "J_PVI_TYPE": "PropVInput@0",
    "3": "PropVInput",
    "J_PVO_TYPE": "PropVOutput@0",
    "4": "PropVOutput",
    "J_NDSTAT_TYPE": "NodeStatus@0",
    "12": "NodeStatus",
}

# Graph presets
GRAPH_PRESETS = {
    "Control Voltage": [{"name": "ControlVoltage", "type": "AI"}],
    "Bus Voltage": [
        {"name": "LH VFD Link Volts", "type": "VFD"},
        {"name": "RH VFD Link Volts", "type": "VFD"}
    ],
    "Pump Amps": [
        {"name": "LPumpPhaseA", "type": "AI"},
        {"name": "LPumpPhaseB", "type": "AI"},
        {"name": "LPumpPhaseC", "type": "AI"},
        {"name": "RPumpPhaseA", "type": "AI"},
        {"name": "RPumpPhaseB", "type": "AI"},
        {"name": "RPumpPhaseC", "type": "AI"},
    ],
    "Lumpbreaker Amps": [
        {"name": "LumpBkrPhaseA", "type": "AI"}, 
        {"name": "LumpBkrPhaseB", "type": "AI"}, 
        {"name": "LumpBkrPhaseC", "type": "AI"},
    ],
    "Haulage Amps": [
        {"name": "LTramPhaseA", "type": "AI"},
        {"name": "LTramPhaseB", "type": "AI"},
        {"name": "LTramPhaseC", "type": "AI"},
        {"name": "RTramPhaseA", "type": "AI"},
        {"name": "RTramPhaseB", "type": "AI"},
        {"name": "RTramPhaseC", "type": "AI"},
    ],
    "Cutter Amps": [
        {"name": "LCutterPhaseA", "type": "AI"},
        {"name": "LCutterPhaseB", "type": "AI"},
        {"name": "LCutterPhaseC", "type": "AI"},
        {"name": "RCutterPhaseA", "type": "AI"},
        {"name": "RCutterPhaseB", "type": "AI"},
        {"name": "RCutterPhaseC", "type": "AI"},
    ],
    "Controller Temps": [{"name": "ControllerRTD", "type": "AI"}],
    "Hydraulic Flow & Pressure": [
        {"name": "rHydraulicPress", "type": "AI"},
        {"name": "lHydraulicPress", "type": "AI"},
        {"name": "lHydraulicFlow", "type": "AI"},
        {"name": "rHydraulicFlow", "type": "AI"},
    ],
    "Auxilary Temps": [
        {"name": "lAux1Temp", "type": "AI"},
        {"name": "lAux2Temp", "type": "AI"},
        {"name": "rAux1Temp", "type": "AI"},
        {"name": "rAux2Temp", "type": "AI"},
    ],
    "Machine Position": [
        {"name": "SupportNo_LH", "type": "AI"},
        {"name": "SupportNo_RH", "type": "AI"},
        {"name": "SupportNo", "type": "AI"},
    ],
    "Drum Water Flow & Pressure": [
        {"name": "lDrumH2OFlow", "type": "AI"},
        {"name": "rDrumH2OFlow", "type": "AI"},
        {"name": "lDrumH2OPress", "type": "AI"},
        {"name": "rDrumH2OPress", "type": "AI"},
    ],
    "Line Voltage": [
        {"name": "LineVoltageA", "type": "AI"},
        {"name": "LineVoltageB", "type": "AI"},
        {"name": "LineVoltageC", "type": "AI"},
    ],
    "Haulage Voltage": [
        {"name": "LH VFD Motor Volts", "type": "VFD"},
        {"name": "RH VFD Motor Volts", "type": "VFD"},
    ],
    "Pump Temp": [
        {"name": "LPumpRTD", "type": "AI"},
        {"name": "RPumpRTD", "type": "AI"},
    ],
    "Lumpbreaker Temp": [{"name": "LumpBkrRTD", "type": "AI"}],
    "Haulage Temp": [
        {"name": "LTramRTD", "type": "AI"},
        {"name": "RTramRTD", "type": "AI"},
    ],
    "Cutter Temp": [
        {"name": "LCutterRTD", "type": "AI"},
        {"name": "RCutterRTD", "type": "AI"},
    ],
    "Arm Bearing Temp": [
        {"name": "lRangingarmTemp", "type": "AI"},
        {"name": "rRangingarmTemp", "type": "AI"},
    ],
    "Trail Cable Strain Guage": [{"name": "TrlCblStrnGauge", "type": "AI"}],
    "Hyd Oil Temp": [
        {"name": "lOilTemp", "type": "AI"},
        {"name": "rOilTemp", "type": "AI"},
    ],
    "Haulage Speeds": [
        {"name": "VFDDesSpeed", "type": "AI"},
        {"name": "VFDActSpeed", "type": "AI"},
    ],
    "Currents & Speeds": [
        {"name": "LTramPhaseA", "type": "AI"},
        {"name": "LTramPhaseB", "type": "AI"},
        {"name": "LTramPhaseC", "type": "AI"},
        {"name": "RTramPhaseA", "type": "AI"},
        {"name": "RTramPhaseB", "type": "AI"},
        {"name": "RTramPhaseC", "type": "AI"},
        {"name": "LCutterPhaseA", "type": "AI"},
        {"name": "LCutterPhaseB", "type": "AI"},
        {"name": "LCutterPhaseC", "type": "AI"},
        {"name": "RCutterPhaseA", "type": "AI"},
        {"name": "RCutterPhaseB", "type": "AI"},
        {"name": "RCutterPhaseC", "type": "AI"},
        {"name": "VFDDesSpeed", "type": "AI"},
        {"name": "VFDActSpeed", "type": "AI"},
    ],
}
